server:
  port: 8082

spring:
  application:
    name: authentication

jwt:
  secret: mdGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCBhdXRoZW50aWNhdGlvbg==
  expiration: 86400000

services:
  user:
    url: http://localhost:8081