spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: AdminPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081

jwt:
  secret: mdGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCBhdXRoZW50aWNhdGlvbg==
  expiration: 86400000

app:
  admin:
    username: admin
    email: admin@example.com
    password: AdminPassword123

services:
  authentication:
    internal-token: change-me-authentication-user-token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
