server:
  port: 8086

spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: AdminPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.microservices.ecommerce.order.dto.PaymentResultEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderPlacedEvent:com.microservices.ecommerce.order.dto.OrderPlacedEvent

kafka:
  topic:
    order-placed: order-placed
    payment-result: payment-result



jwt:
  secret: mdGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCBhdXRoZW50aWNhdGlvbg==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

services:
  cart:
    internal-token: change-me-cart-user-token
  product:
    internal-token: change-me-product-order-token
