server:
  port: 8086

spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: AdminPassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mdGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCBhdXRoZW50aWNhdGlvbg==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

services:
  cart:
    internal-token: change-me-cart-user-token
  product:
    internal-token: change-me-product-order-token
